num = int(input('Digite um número para ver a tabuada:'))
print('-' * 12)
print('{} x {:2} = {}'.format(num, 1, num*1))
print('{} x {:2} = {}'.format(num, 1, num*2))
print('{} x {:2} = {}'.format(num, 1, num*3))
print('{} x {:2} = {}'.format(num, 1, num*4))
print('{} x {:2} = {}'.format(num, 1, num*5))
print('{} x {:2} = {}'.format(num, 1, num*6))
print('{} x {:2} = {}'.format(num, 1, num*7))
print('{} x {:2} = {}'.format(num, 1, num*8))
print('{} x {:2} = {}'.format(num, 1, num*9))
print('{} x {:2} = {}'.format(num, 1, num*10))
print('-' * 12)
